# Build from monorepo root:
#   gcloud builds submit --config=cloudbuild.yaml .
#
# Or from gymbuddy-api (use . as source, not gymbuddy-api):
#   cd gymbuddy-api && gcloud builds submit --tag gcr.io/soultrust-gymbuddy/gymbuddy-api .

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/soultrust-gymbuddy/gymbuddy-api", "./gymbuddy-api"]
images:
  - "gcr.io/soultrust-gymbuddy/gymbuddy-api"
