# Generated by Django 6.0.2 on 2026-02-21 03:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_add_program_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkoutSession",
            new_name="Session",
        ),
        migrations.RenameField(
            model_name="performedexercise",
            old_name="workout",
            new_name="session",
        ),
        migrations.AlterUniqueTogether(
            name="performedexercise",
            unique_together={("session", "order")},
        ),
    ]
